### ISSUE TITLE
Can I ask what you think pushes this version so far above this other implementation?

### ISSUE THREAD

**Issue by slerman12** [omihub777/ViT-CIFAR#5]
Here is the other: https://github.com/kentaroy47/vision-transformers-cifar10

**Comment by slerman12** [comment]
Mainly I'm just trying to figure out what the key difference is. Without AutoAugment and the scheduled learning rate (keeping it fixed at 1e-4), just those two changes, the performance falls below 82% using another piece of code. Do you know if those tricks/techniques are critical or if maybe something is just wrong about the other implementation? Sorry, I can't test this one right now, so I'm wondering if you know already off the top of your head. Thanks.

**Comment by arash1902** [comment]
I also noticed similar behavior in your MLP-Mixer implementation and training. I cannot train other models with a performance better than 83% while you report ~90% accuracy. So, I am also interested to know if you have any insight on this.

**Comment by omihub777** [comment]
> Can I ask what you think pushes this version so far above this other implementation?

Sorry for the belated reply. Besides @slerman12's comment, I also noticed performance gains from CutMix were substantial during my experiments. (Label smoothing also gives marginal improvement.)

> Do you know if those tricks/techniques are critical or if maybe something is just wrong about the other implementation? 

I would say those tricks are critical based on my experiments. I don't think other implementations are wrong because my implementation also works pretty badly without any data augmentations/tricks.
